#!/usr/bin/env bash
# AminoCloud standardized entrypoint — generated by seed-ac-dirs.sh
# Runtime environment variables (injected by the AC pipeline worker):
#   AC_INPUT_<PORT_ID_UPPER>   path to each declared input file/dir
#   AC_OUTPUT_DIR              write all outputs here
#   AC_CPU_THREADS             allocated vCPU count (integer)
#   AC_MEMORY_GB               allocated memory in GB (integer)
#   AC_JOB_ID                  pipeline job UUID (for log correlation)
#   AC_STEP_ID                 job step UUID (for log correlation)
set -euo pipefail
mkdir -p "${AC_OUTPUT_DIR}"

# Build Bowtie2 index from FASTA if .1.bt2 is absent
INDEX_PREFIX="${AC_OUTPUT_DIR}/ref_index"
if [[ ! -f "${INDEX_PREFIX}.1.bt2" ]]; then
    bowtie2-build --threads "${AC_CPU_THREADS}" \
        "${AC_INPUT_REF_IN}" "${INDEX_PREFIX}"
fi

bowtie2 \
    -p "${AC_CPU_THREADS}" \
    -x "${INDEX_PREFIX}" \
    -U "${AC_INPUT_FASTQ_IN}" \
    -S "${AC_OUTPUT_DIR}/aligned.sam"
